// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace demoaspcore.Models
{
    public partial class QLNhanVienContext : DbContext
    {
        public QLNhanVienContext()
        {
        }

        public QLNhanVienContext(DbContextOptions<QLNhanVienContext> options)
: base(options)
        {
        }

        public virtual DbSet<TChiTietNhanVien> TChiTietNhanVien { get; set; }
        public virtual DbSet<TNhanVien> TNhanVien { get; set; }
        public virtual DbSet<TPhongBan> TPhongBan { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TChiTietNhanVien>(entity =>
            {
                entity.HasKey(e => e.MaNv);

                entity.ToTable("tChiTietNhanVien");

                entity.Property(e => e.MaNv)
                    .HasMaxLength(3)
                    .HasColumnName("MaNV");

                entity.Property(e => e.ChucVu).HasMaxLength(3);

                entity.Property(e => e.Gtgc).HasColumnName("GTGC");

                entity.Property(e => e.Hsluong).HasColumnName("HSLuong");

                entity.Property(e => e.MucDoCv)
                    .HasMaxLength(2)
                    .HasColumnName("MucDoCV");

                entity.HasOne(d => d.MaNvNavigation)
                    .WithOne(p => p.TChiTietNhanVien)
                    .HasForeignKey<TChiTietNhanVien>(d => d.MaNv)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tChiTietNhanVien_tNhanVien");
            });

            modelBuilder.Entity<TNhanVien>(entity =>
            {
                entity.HasKey(e => e.MaNv);

                entity.ToTable("tNhanVien");

                entity.Property(e => e.MaNv)
                    .HasMaxLength(3)
                    .HasColumnName("MaNV");

                entity.Property(e => e.Ghichu).HasColumnName("GHICHU");

                entity.Property(e => e.Hinh)
                    .HasColumnType("image")
                    .HasColumnName("HINH");

                entity.Property(e => e.Ho)
                    .HasMaxLength(15)
                    .HasColumnName("HO");

                entity.Property(e => e.MaPb)
                    .HasMaxLength(2)
                    .HasColumnName("MaPB");

                entity.Property(e => e.NgayBd)
                    .HasColumnType("datetime")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.Ntns)
                    .HasColumnType("datetime")
                    .HasColumnName("NTNS");

                entity.Property(e => e.Phai).HasColumnName("PHAI");

                entity.Property(e => e.Ten)
                    .HasMaxLength(7)
                    .HasColumnName("TEN");

                entity.HasOne(d => d.MaPbNavigation)
                    .WithMany(p => p.TNhanVien)
                    .HasForeignKey(d => d.MaPb)
                    .HasConstraintName("FK_tNhanVien_tPhongBan1");
            });

            modelBuilder.Entity<TPhongBan>(entity =>
            {
                entity.HasKey(e => e.MaPb);

                entity.ToTable("tPhongBan");

                entity.Property(e => e.MaPb)
                    .HasMaxLength(2)
                    .HasColumnName("MaPB");

                entity.Property(e => e.Tenpb)
                    .HasMaxLength(30)
                    .HasColumnName("TENPB");

                entity.Property(e => e.TruongPhong).HasMaxLength(3);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}