// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace demoaspcore.Models
{
    public partial class TNhanVien
    {
        public string MaNv { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public bool Phai { get; set; }
        public DateTime? Ntns { get; set; }
        public DateTime? NgayBd { get; set; }
        public string MaPb { get; set; }
        public byte[] Hinh { get; set; }
        public string Ghichu { get; set; }

        public virtual TPhongBan MaPbNavigation { get; set; }
        public virtual TChiTietNhanVien TChiTietNhanVien { get; set; }
    }
}