//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietHoaDon
    {
        public string SoHD { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaDichVu { get; set; }
    
        public virtual tDichVu tDichVu { get; set; }
        public virtual tHoaDon tHoaDon { get; set; }
    }
}
