//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHoaDon()
        {
            this.tChiTietHoaDons = new HashSet<tChiTietHoaDon>();
        }
    
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public Nullable<decimal> TongTienHoaDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHoaDon> tChiTietHoaDons { get; set; }
        public virtual tKhachHang tKhachHang { get; set; }
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
