//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLichChieu()
        {
            this.tVes = new HashSet<tVe>();
        }
    
        public string MaPhongChieu { get; set; }
        public string MaPhim { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public Nullable<int> SLDaBan { get; set; }
        public string KhuyenMai { get; set; }
    
        public virtual tPhim tPhim { get; set; }
        public virtual tPhongChieu tPhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVe> tVes { get; set; }
    }
}
