//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNhanVien()
        {
            this.tHoaDons = new HashSet<tHoaDon>();
            this.tVes = new HashSet<tVe>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<int> SoDT { get; set; }
        public bool GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> SLVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHoaDon> tHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVe> tVes { get; set; }
    }
}
