//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPhim()
        {
            this.tLichChieux = new HashSet<tLichChieu>();
        }
    
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string NoiDungPhim { get; set; }
        public Nullable<decimal> GiaPhim { get; set; }
        public Nullable<int> ThoiLuongPhim { get; set; }
        public string DaoDien { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> TongThu { get; set; }
        public string MaHangSX { get; set; }
        public string MaNuocSX { get; set; }
        public string MaTheLoai { get; set; }
        public string Anh { get; set; }
    
        public virtual tHangSX tHangSX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLichChieu> tLichChieux { get; set; }
        public virtual tNuocSX tNuocSX { get; set; }
        public virtual tTheLoai tTheLoai { get; set; }
    }
}
