//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVe
    {
        public string MaVe { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public string LoaiVe { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
    
        public virtual tKhachHang tKhachHang { get; set; }
        public virtual tLichChieu tLichChieu { get; set; }
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
