//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view2
    {
        public System.DateTime NgayChieu { get; set; }
        public string MaPhongChieu { get; set; }
        public Nullable<int> TongSoGhe { get; set; }
        public Nullable<int> SoGheConTrong { get; set; }
    }
}
